Server:
  listen:
    - host: 127.0.0.1
      port: 8000

Routing:
  routing: !Prefix
  routing-by: !Path
  map:
    /*:
      zmq-forward:
        enabled: yes
        socket: !zmq.Req
        - !zmq.Bind ipc://./run/http.sock
        contents:
        - !Uri
        - !Header Content-Type
        - !Body
    /js/*: &static
      static:
        enabled: yes
        root: ./public
        restrict-root: no
    /css/*: *static

